CLEARSCREEN.
SAS ON.
PRINT "TEST".

WHEN SHIP:ALTITUDE < 500 THEN {
	PRINT ROUND(SHIP:ALTITUDE,2) + " m" AT(2,3).
	PRESERVE.
}

WHEN SHIP:AIRSPEED < 100 THEN {
	PRINT ROUND(SHIP:AIRSPEED,2) + " m/s     " AT (2,4).
	PRESERVE.
}

UNTIL SHIP:ALTITUDE > 1000 {
	PRINT "RUNNING " + ROUND(TIME:SECONDS) AT(20,1).
}

PRINT "ALL DONE.          " AT(20,1).