CLEARSCREEN.
SAS ON.
PRINT "TEST".

WHEN SHIP:ALTITUDE < 500 THEN {
	PRINT SHIP:ALTITUDE AT(2,3).
	PRESERVE.
}

WHEN SHIP:AIRSPEED < 100 THEN {
	PRINT SHIP:AIRSPEED AT (2,4).
	PRESERVE.
}

UNTIL SHIP:ALTITUDE > 1000 {
	PRINT "RUNNING" AT(20,1).
}

PRINT "ALL DONE." AT(2,7).